name: Terraform Validate
on:
  push:
    branches:
      - main
      - master
  # pull_request:

env:
  TERRAFORM_VERSION: 1.1.7
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Init
        uses: hashicorp/terraform-github-actions@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_working_dir: .
          tf_actions_comment: true
          tf_actions_subcommand: init
      - name: Validate
        uses: hashicorp/terraform-github-actions@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_working_dir: .
          tf_actions_comment: true
          tf_actions_subcommand: validate
